function getData() {
    return data = [
        "./img/1.jpg", "小白",
        "./img/1.jpg", "小黑",
        "./img/1.jpg", "小明",
        "./img/1.jpg", "晓得",
        "./img/1.jpg", "小李",
        "./img/1.jpg", "小胡",
        "./img/1.jpg", "小黄",
        "./img/1.jpg", "小智",
        "./img/1.jpg", "小新",
        "./img/1.jpg", "汪仔",
        "./img/1.jpg", "小白",
        "./img/1.jpg", "小黑",
        "./img/1.jpg", "小明",
        "./img/1.jpg", "晓得",
        "./img/1.jpg", "小李",
        "./img/1.jpg", "小胡",
        "./img/1.jpg", "小黄",
        "./img/1.jpg", "小智",
        "./img/1.jpg", "小新",
        "./img/1.jpg", "汪仔",
        "./img/1.jpg", "小白",
        "./img/1.jpg", "小黑",
        "./img/1.jpg", "小明",
        "./img/1.jpg", "晓得",
        "./img/1.jpg", "小李",
        "./img/1.jpg", "小胡",
        "./img/1.jpg", "小黄",
        "./img/1.jpg", "小智",
        "./img/1.jpg", "小新",
        "./img/1.jpg", "汪仔",
    ];
}